apiVersion: v1
kind: Secret
metadata:
  name: hackaton-secret
  namespace: hackaton
type: Opaque
stringData:
  DB_HOST: "ep-falling-pond-atsm99qj.c-9.us-east-1.aws.neon.tech"
  DB_PORT: "5432"
  DB_NAME: "neondb"
  DB_USER: "neondb_owner"
  DB_PASSWORD: "npg_ahoDeY8LT9Xy"
  DB_SSL_MODE: "require"
  R2DBC_URL: "r2dbc:postgresql://ep-falling-pond-atsm99qj.c-9.us-east-1.aws.neon.tech/neondb?sslMode=require"
